spring:
  security:
    oauth2:
      client:
        registration:
          google:
            scope: email
            client-id:
            client-secret:
          naver:
            client-id:
            client-secret:
            scope: name, email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
